version: "3.3"
services:
  web:
    build: ./frontend/app
    working_dir: /home/frontend
    environment:
      - NODE_ENV=production
    ports:
      - "8080:80"
    volumes:
      - ./frontend/app:/home/frontend