framework:
    cache:
        # Put the unique name of your server here: the prefix seed
        # is used to compute stable namespaces for cache keys.
        #prefix_seed: your_vendor_name/app_name

        # The server cache caches to the filesystem by default.
        # Other options include:

        # Redis
        #server: cache.adapter.redis
        #default_redis_provider: redis://localhost

        # APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
        #server: cache.adapter.apcu

        # Namespaced pools use the above "server" backend by default
        #pools:
            #my.dedicated.cache: ~
