# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the server is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: false      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Domain,Infrastructure/Migrations,Application,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Infrastructure\Controller\:
        resource: '../src/Infrastructure/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Infrastructure\Repository\Post\DoctrinePostRepository:
        arguments:
            - '@Symfony\Bridge\Doctrine\RegistryInterface'

    App\Application\Post\Read\AllPosts:
        arguments:
            - '@App\Infrastructure\Repository\Post\DoctrinePostRepository'

    App\Infrastructure\Controller\Posts\SymfonyGetAllPosts:
        arguments:
            - '@App\Application\Post\Read\AllPosts'
            - '@App\Infrastructure\DataTransformer\Post\JsonPostDataTransformer'
        tags: ['controller.service_arguments']

    App\Infrastructure\Repository\User\DoctrineUserRepository:
        arguments:
            - '@Symfony\Bridge\Doctrine\RegistryInterface'

    App\Application\User\QueryHandler\ReadUserQueryHandler:
        arguments:
            - '@App\Infrastructure\Repository\User\DoctrineUserRepository'

    App\Application\User\Read\ReadUser:
        arguments:
            - '@App\Application\User\QueryHandler\ReadUserQueryHandler'
            - '@App\Infrastructure\Encoder\BcryptUserEncoder'

    App\Infrastructure\Controller\Users\SymfonyGetUser:
        arguments:
            - '@App\Application\User\Read\ReadUser'
        tags: ['controller.service_arguments']

    App\Domain\User\UserFactory:
        arguments:
            - '@App\Infrastructure\Generator\UuidCodeGenerator'
            - '@App\Infrastructure\Repository\User\DoctrineUserRepository'

    App\Application\User\Create\CreateUser:
        arguments:
            - '@App\Domain\User\UserFactory'
            - '@App\Infrastructure\Repository\User\DoctrineUserRepository'

    App\Infrastructure\Controller\Users\SymfonyCreateUser:
        arguments:
            - '@App\Application\User\Create\CreateUser'
        tags: ['controller.service_arguments']

    App\Application\User\Delete\DeleteUser:
        arguments:
            - '@App\Infrastructure\Repository\User\DoctrineUserRepository'

    App\Infrastructure\Controller\Users\SymfonyDeleteUser:
        arguments:
            - '@App\Application\User\Delete\DeleteUser'
        tags: ['controller.service_arguments']

    App\Application\User\Update\UpdateUser:
        arguments:
            - '@App\Infrastructure\Repository\User\DoctrineUserRepository'

    App\Infrastructure\Controller\Users\SymfonyUpdateUser:
        arguments:
            - '@App\Application\User\Update\UpdateUser'
        tags: ['controller.service_arguments']

    App\Infrastructure\Repository\Muscle\DoctrineMuscleRepository:
        arguments:
            - '@Symfony\Bridge\Doctrine\RegistryInterface'

    App\Domain\Muscle\MuscleFactory:
        arguments:
            - '@App\Infrastructure\Generator\UuidCodeGenerator'

    App\Application\Muscle\Create\CreateMuscle:
        arguments:
            - '@App\Infrastructure\Repository\Muscle\DoctrineMuscleRepository'
            - '@App\Domain\Muscle\MuscleFactory'

    App\Infrastructure\Controller\Muscles\SymfonyImportMuscles:
        arguments:
            - '@App\Application\Muscle\Create\CreateMuscle'
        tags: ['controller.service_arguments']

