App\Domain\Post\Post:
    type: entity
    table: post
    repositoryClass: App\Infrastructure\Repository\Post\DoctrinePostRepository
    id:
      id:
        type: integer
        unique: true
        generator:
          strategy: AUTO
    fields:
      string:
        type: string
        length: 255
      created:
        type: datetime
        nullable: false
      updated:
        type: datetime
        nullable: true