App\Domain\User\User:
    type: entity
    table: user
    repositoryClass: App\Infrastructure\Repository\User\DoctrineUserRepository
    id:
      uuid:
          type: string
          length: 36
          unique: true
          generator:
            strategy: NONE
    fields:
      username:
        type: string
        length: 255
        nullable: false
      password:
        type: string
        length: 255
        nullable: false
      email:
        type: string
        length: 50
        nullable: false
      createdDate:
        type: datetime
        nullable: true
      updatedDate:
        type: datetime
        nullable: true