efaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
        [entryPoints.https.tls]
  [entryPoints.api]
  address = ":8080"

[api]
entryPoint = "api"

[acme]
entryPoint = "https"
storage = "/etc/traefik/acme/acme.json"
caServer = "https://acme-v02.api.letsencrypt.org/directory"
  [acme.dnsChallenge]
  provider = "cloudflare"
  delayBeforeCheck = 0
  [[acme.domains]]
  main = "*.app.localhost"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "app.localhost"
exposedByDefault = false
swarmmode = false
#
#[file]
#watch = true
#
#[backends]
#  [backends.server]
#    [backends.server.servers]
#      [backends.server.servers.server]
#      url = "http://192.168.100.100"
#      weight = 10
#
#[frontends]
#  [frontends.client]
#  backend = "server"
#    [frontends.client.routes]
#      [frontends.client.routes.client]
#      rule = "Host:client.app.localhost"